// Generated by tools/gen_palette_lut.py -- do not edit.
//
// Index is {r[1:0], g[1:0], b[1:0]} straight off the two colour PROMs.
// Value is the 24-bit RGB MAME produces after its resistor-network model
// and normalize_range, which is verified pen-for-pen against every
// supported romset by the generator.

localparam logic [23:0] PAL_LUT [0:63] = '{
    24'h000000,  // 0 0 0
    24'h000000,  // 0 0 1
    24'h070691,  // 0 0 2
    24'h0A07BD,  // 0 0 3
    24'h000000,  // 0 1 0
    24'h000000,  // 0 1 1
    24'h070691,  // 0 1 2
    24'h0A07BD,  // 0 1 3
    24'h23AD24,  // 0 2 0
    24'h23AD24,  // 0 2 1
    24'h2AB5B6,  // 0 2 2
    24'h2DB8E0,  // 0 2 3
    24'h2EDF2D,  // 0 3 0
    24'h2EDF2D,  // 0 3 1
    24'h35E7BF,  // 0 3 2
    24'h36E8E9,  // 0 3 3
    24'h000000,  // 1 0 0
    24'h000000,  // 1 0 1
    24'h070691,  // 1 0 2
    24'h0A07BD,  // 1 0 3
    24'h000000,  // 1 1 0
    24'h000000,  // 1 1 1
    24'h070691,  // 1 1 2
    24'h0A07BD,  // 1 1 3
    24'h23AD24,  // 1 2 0
    24'h23AD24,  // 1 2 1
    24'h2AB5B6,  // 1 2 2
    24'h2DB8E0,  // 1 2 3
    24'h2EDF2D,  // 1 3 0
    24'h2EDF2D,  // 1 3 1
    24'h35E7BF,  // 1 3 2
    24'h36E8E9,  // 1 3 3
    24'h9F1114,  // 2 0 0
    24'h9F1114,  // 2 0 1
    24'hA518A5,  // 2 0 2
    24'hA71BCE,  // 2 0 3
    24'h9F1114,  // 2 1 0
    24'h9F1114,  // 2 1 1
    24'hA518A5,  // 2 1 2
    24'hA71BCE,  // 2 1 3
    24'hC0C136,  // 2 2 0
    24'hC0C136,  // 2 2 1
    24'hC8C8C8,  // 2 2 2
    24'hCCCAF1,  // 2 2 3
    24'hCDF040,  // 2 3 0
    24'hCDF040,  // 2 3 1
    24'hD4F7D5,  // 2 3 2
    24'hD5FBF9,  // 2 3 3
    24'hCA1618,  // 3 0 0
    24'hCA1618,  // 3 0 1
    24'hD11EAA,  // 3 0 2
    24'hD31FD2,  // 3 0 3
    24'hCA1618,  // 3 1 0
    24'hCA1618,  // 3 1 1
    24'hD11EAA,  // 3 1 2
    24'hD31FD2,  // 3 1 3
    24'hEDC63A,  // 3 2 0
    24'hEDC63A,  // 3 2 1
    24'hF4CDCF,  // 3 2 2
    24'hF5D0F5,  // 3 2 3
    24'hF6F644,  // 3 3 0
    24'hF6F644,  // 3 3 1
    24'hFDFDD9,  // 3 3 2
    24'hFFFFFF  // 3 3 3
};
