#!/usr/bin/env python3
"""Generate rtl/phoenix_palette_lut.svh and prove it equals MAME's palette.

MAME builds the palette by running each pen's two PROM bits per channel through
a resistor-network model in floating point and then stretching the result's
luminance across the full range. Neither step belongs in gateware.

It does not have to be. The ladder has only four input codes per channel and
they map to just three voltages, so the whole thing collapses to a function of
the 6-bit (r,g,b) value the two PROMs produce -- 64 entries, which is a LUT.

The luminance stretch depends on the darkest and brightest colours in the
palette, so in principle it is per-game. In practice every Phoenix-family PROM
set contains both `(0,0,0)` and `(3,3,3)`, which pin ymin and ymax to the same
constants, and the LUT comes out identical for Pleiads and Phoenix. This script
checks that claim against each ROM it is given rather than assuming it, and
fails if a romset ever breaks it.

Usage: gen_palette_lut.py [game.rom ...]
"""
import sys, os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import importlib.util as iu
_s = iu.spec_from_file_location('rm', os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                   'render_model.py'))
rm = iu.module_from_spec(_s); _s.loader.exec_module(rm)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The extremes any Phoenix PROM set contains: raw (5,5,5) and (186,186,186).
YMIN, YMAX = 5 * 1000, 186 * 1000


def lut64():
    """(r2,g2,b2) 2-bit codes -> normalised 24-bit RGB, all 64 combinations."""
    lv = [rm.compute_res_net(i) for i in range(4)]        # [5, 5, 147, 186]
    raw = [(lv[i >> 4 & 3], lv[i >> 2 & 3], lv[i & 3]) for i in range(64)]
    out = []
    for (r, g, b) in raw:
        y = 299 * r + 587 * g + 114 * b
        u = rm._trunc_div((b - rm._trunc_div(y, 1000)) * 492, 1000)
        v = rm._trunc_div((r - rm._trunc_div(y, 1000)) * 877, 1000)
        target = rm._trunc_div((y - YMIN) * 256, YMAX - YMIN)
        out.append((rm._clamp(target + rm._trunc_div(1140 * v, 1000)),
                    rm._clamp(target - rm._trunc_div(395 * u, 1000)
                                     - rm._trunc_div(581 * v, 1000)),
                    rm._clamp(target + rm._trunc_div(2032 * u, 1000))))
    return out


def check(rom_path, table):
    """The LUT must reproduce MAME's palette for this romset, pen for pen."""
    rom = open(rom_path, 'rb').read()
    game = rm.GAME_BY_SUM.get(sum(rom[rm.PROG:rm.PROG + rm.PROG_LEN]) & 0xFFFFFFFF)
    if game is None:
        print(f'  {os.path.basename(rom_path)}: unknown game, skipped')
        return True
    proms = rom[rm.PROMS:rm.PROMS + 0x200]
    want = rm.build_palette(proms, game)
    bad = 0
    for pen in range(256):
        i = pen
        if game == 'phoenix':
            col = (((i >> 6) & 1) << 6 | ((i >> 5) & 1) << 5 | ((i >> 1) & 1) << 4 |
                   ((i >> 0) & 1) << 3 | ((i >> 4) & 1) << 2 | ((i >> 3) & 1) << 1 |
                   ((i >> 2) & 1))
        else:
            col = (((i >> 7) & 1) << 7 | ((i >> 6) & 1) << 6 | ((i >> 5) & 1) << 5 |
                   ((i >> 1) & 1) << 4 | ((i >> 0) & 1) << 3 | ((i >> 4) & 1) << 2 |
                   ((i >> 3) & 1) << 1 | ((i >> 2) & 1))
        p0, p1 = proms[col], proms[256 + col]
        code = ((((p0 >> 0) & 1) | ((p1 << 1) & 2)) << 4 |
                (((p0 >> 2) & 1) | ((p1 >> 1) & 2)) << 2 |
                (((p0 >> 1) & 1) | ((p1 >> 0) & 2)))
        if table[code] != want[pen]:
            bad += 1
    status = 'ok' if bad == 0 else f'{bad} PENS DIFFER'
    print(f'  {game:8s} ({os.path.basename(rom_path)}): {status}')
    return bad == 0


def main():
    table = lut64()
    roms = sys.argv[1:] or [os.path.join(ROOT, f'{g}.rom') for g in ('pleiads', 'phoenix')]
    roms = [r for r in roms if os.path.exists(r)]
    print('checking the 64-entry LUT against MAME\'s palette:')
    if not all(check(r, table) for r in roms):
        sys.exit('LUT does not reproduce MAME\'s palette -- do not ship this')

    out = os.path.join(ROOT, 'rtl/phoenix_palette_lut.svh')
    lines = ['// Generated by tools/gen_palette_lut.py -- do not edit.',
             '//',
             '// Index is {r[1:0], g[1:0], b[1:0]} straight off the two colour PROMs.',
             '// Value is the 24-bit RGB MAME produces after its resistor-network model',
             '// and normalize_range, which is verified pen-for-pen against every',
             '// supported romset by the generator.',
             '',
             'localparam logic [23:0] PAL_LUT [0:63] = \'{']
    for i, (r, g, b) in enumerate(table):
        c = ',' if i < 63 else ''
        lines.append(f"    24'h{r:02X}{g:02X}{b:02X}{c}"
                     f"  // {i>>4&3} {i>>2&3} {i&3}")
    lines.append('};')
    open(out, 'w').write('\n'.join(lines) + '\n')
    print(f'wrote {out} (64 entries)')


if __name__ == '__main__':
    main()
