#!/usr/bin/env python3
"""Generate rtl/tms36xx_tunes.svh from MAME's tms36xx.cpp.

The note and melody tables are parsed out of the MAME source rather than
transcribed, for the same reason the palette LUT is: a table copied by hand is
a table that can be copied wrong, and nothing downstream would notice.

tune4 is the thirteen-tone note table the TMS3615 plays from, which is what
Pleiads uses -- the game writes a note number to sound latch B and the chip
plays it. tunes 1 to 3 are the MM6221AA's built-in melodies, which Phoenix
uses; they are emitted too so the Phoenix sound section has them ready.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'ref/mame/tms36xx.cpp')
FSCALE = 1024

# The note macros, straight from the top of tms36xx.cpp.
RATIO = {'C': 1.18921, 'Cx': 1.25992, 'D': 1.33484, 'Dx': 1.41421,
         'E': 1.49831, 'F': 1.58740, 'Fx': 1.68179, 'G': 1.78180,
         'Gx': 1.88775, 'Ax': 1.05946, 'B': 1.12246}


def note_value(name, n):
    if name == 'A':
        return int(FSCALE << n)
    if name in ('Ax', 'B'):
        return int((FSCALE << n) * RATIO[name])
    return int((FSCALE << (n - 1)) * RATIO[name])


def parse_tune(src, name):
    m = re.search(rf'{name}\[(\d+)\*6\]\s*=\s*\{{(.*?)\}};', src, re.S)
    if not m:
        sys.exit(f'could not find {name} in {SRC}')
    rows, body = int(m.group(1)), re.sub(r'/\*.*?\*/', '', m.group(2), flags=re.S)
    vals = []
    for tok in re.findall(r'([A-G]x?)\((\d+)\)|(\b0\b)', body):
        if tok[2]:
            vals.append(0)
        else:
            vals.append(note_value(tok[0], int(tok[1])))
    # The arrays are declared [n*6] but several are only partly initialised --
    # tune1 lists 32 rows of a declared 96. C zero-fills the rest, and the
    # chip reads the whole declared length, so pad rather than complain.
    if len(vals) > rows * 6:
        sys.exit(f'{name}: parsed {len(vals)} entries, more than the declared {rows * 6}')
    vals += [0] * (rows * 6 - len(vals))
    return vals


def main():
    src = open(SRC).read()
    tunes = {n: parse_tune(src, n) for n in ('tune1', 'tune2', 'tune3', 'tune4')}

    out = [
        '// Generated by tools/gen_tune_tables.py from ref/mame/tms36xx.cpp.',
        '// Do not edit.',
        '//',
        '// Values are the raw entries of MAME\'s tune tables, already through the',
        '// C(n)/D(n)/... macros. The chip turns one into a voice frequency with',
        '//',
        '//     frequency = entry * (basefreq << octave) / 1024',
        '//',
        '// which is a multiply and a shift, so the tables stay small.',
        '',
        f'localparam int TMS_TUNE4_NOTES = {len(tunes["tune4"]) // 6};',
        f"localparam logic [15:0] TMS_TUNE4 [0:{len(tunes['tune4']) - 1}] = '{{",
    ]
    for i, v in enumerate(tunes['tune4']):
        out.append(f"    16'd{v}{',' if i < len(tunes['tune4']) - 1 else ''}")
    out.append('};')
    out.append('')
    for name in ('tune1', 'tune2', 'tune3'):
        vals = tunes[name]
        out.append(f'// {name}: an MM6221AA melody, used by Phoenix.')
        out.append(f'localparam int TMS_{name.upper()}_LEN = {len(vals)};')
        out.append(f"localparam logic [15:0] TMS_{name.upper()} [0:{len(vals) - 1}] = '{{")
        for i, v in enumerate(vals):
            out.append(f"    16'd{v}{',' if i < len(vals) - 1 else ''}")
        out.append('};')
        out.append('')

    path = os.path.join(ROOT, 'rtl/tms36xx_tunes.svh')
    open(path, 'w').write('\n'.join(out) + '\n')
    print(f'wrote {path}: ' +
          ', '.join(f'{n} {len(v)} entries' for n, v in tunes.items()))


if __name__ == '__main__':
    main()
