#!/usr/bin/env python3
"""Generate rtl/phoenix_555_lut.svh: 555 astable frequency against control
voltage, for the two control-voltage oscillators in Phoenix's discrete netlist.

MAME simulates these at the capacitor, integrating the charge and discharge
exponentials. That is faithful and it is also a logarithm in the inner loop.
Every 555 here is a *clock* whose divided output is what reaches the speaker,
so only its frequency matters, and for an astable with the control pin driven
the period is closed-form:

    t_high = (R1 + R2) * C * ln((Vch - Vcv/2) / (Vch - Vcv))
    t_low  =       R2  * C * ln(2)

Tabulated against control voltage, that is a lookup and an interpolation.

  IC20 (effect 1): R25 = R26 = 47k, C8  = 1nF
  IC50 (effect 2): R47 = R48 = 20k, C23 = 1nF
"""
import math, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
N = 256                 # entries, indexed by cv in mV scaled to 0..5000
VCH = 5.0


def f555(r1, r2, c, v_cv):
    v_cv = max(0.05, min(VCH - 0.05, v_cv))
    t_hi = (r1 + r2) * c * math.log((VCH - v_cv / 2.0) / (VCH - v_cv))
    t_lo = r2 * c * math.log(2.0)
    return 1.0 / (t_hi + t_lo)


def table(r1, r2, c):
    out = []
    for i in range(N):
        v = (i + 0.5) * VCH / N
        f = f555(r1, r2, c, v)
        out.append(min(0xFFFF, int(round(f))))      # Hz, capped at 65535
    return out


def main():
    t1 = table(47e3, 47e3, 1e-9)
    t2 = table(20e3, 20e3, 1e-9)
    lines = [
        '// Generated by tools/gen_555_lut.py -- do not edit.',
        '//',
        f'// 555 astable frequency in Hz against control voltage, {N} entries',
        f'// spanning 0 to 5 V. Entry i is the frequency at (i + 0.5) * 5000/{N} mV,',
        f'// so the index is cv_mV * {N} / 5000.',
        '//',
        f'// IC20, effect 1: R25 = R26 = 47k, C8 = 1nF  ({t1[0]} to {t1[-1]} Hz)',
        f'// IC50, effect 2: R47 = R48 = 20k, C23 = 1nF ({t2[0]} to {t2[-1]} Hz)',
        '',
        f"localparam logic [15:0] F555_E1 [0:{N-1}] = '{{",
    ]
    lines += [f"    16'd{v}{',' if i < N - 1 else ''}" for i, v in enumerate(t1)]
    lines.append('};')
    lines.append('')
    lines.append(f"localparam logic [15:0] F555_E2 [0:{N-1}] = '{{")
    lines += [f"    16'd{v}{',' if i < N - 1 else ''}" for i, v in enumerate(t2)]
    lines.append('};')
    p = os.path.join(ROOT, 'rtl/phoenix_555_lut.svh')
    open(p, 'w').write('\n'.join(lines) + '\n')
    print(f'wrote {p}')
    print(f'  effect 1: {t1[0]} Hz at 0.04 V .. {t1[-1]} Hz at 4.96 V')
    print(f'  effect 2: {t2[0]} Hz at 0.04 V .. {t2[-1]} Hz at 4.96 V')


if __name__ == '__main__':
    main()
